

repo_url: https://github.com/Pabloserrapxx/Laranja_mec-nica/tree/main
repo_name: Laranja_mec-nica


site_name: Laranja Mecânica

nav:
    - Home: index.md
    - Entendimento do Problema: Entendimento do Problema.md
    - Levantamento e Priorização de Requisitos: 
        - Levantamento de Requistos: requisitos.md
        - Priorização de Requisitos: Levantamento e Priorização de Requisitos.md

    - Modelagem: Pabloserrapxx/Laranja_mec-nica/docs/Modelagem
        
        - Personas: Personas.md
        - Cenarios: cenarios.md
    - Finalização:
        - Conclusão: Finalizacao.md

theme:
    name: material
    custom_dir: "docs"
    palette:
        - scheme: default
          primary: yellow
          accent: yellow
          toggle:
            icon: material/toggle-switch-off-outline
            name: Modo Escuro
        - scheme: slate
          primary: orange
          accent: orange
          toggle:
            icon: material/toggle-switch
            name: Modo Claro
    features:
        
extra_css:
    - css/custom.css
extra_templates:
      - header.html
extra_javascript:
  - extra.js
