name: Deploy MkDocs

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: pip install mkdocs-material

    - name: Deploy MkDocs para GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: mkdocs gh-deploy --force --remote-branch gh-pages
