name: MkDocs Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Setup Git Credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Check Git Remote
        run: git remote -v

      - name: Create gh-pages Branch (if not exists)
        run: |
          git checkout --orphan gh-pages || true
          git commit --allow-empty -m "Initial gh-pages commit" || true
          git push origin gh-pages --force || true
          git checkout - || true

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
